apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::561435029645:user/barakat-dev-view
      username: barakat-dev-view
      groups:
        - system:authenticated